ARG BASE_IMAGE=cgr.dev/chainguard/static:latest
FROM $BASE_IMAGE 

ARG BIN_SUFFIX
COPY keda-adapter${BIN_SUFFIX} /keda-adapter

USER 65532:65532

ENTRYPOINT ["/keda-adapter", "--secure-port=6443", "--logtostderr=true", "--v=0"]
