ARG BASE_IMAGE=cgr.dev/chainguard/static:latest
FROM $BASE_IMAGE 

ARG BIN_SUFFIX
COPY keda-admission-webhooks${BIN_SUFFIX} /keda-admission-webhooks

USER 65532:65532

ENTRYPOINT ["/keda-admission-webhooks", "--zap-log-level=info", "--zap-encoder=console"]
