ARG BASE_IMAGE=cgr.dev/chainguard/static:latest
FROM $BASE_IMAGE 

ARG BIN_SUFFIX
COPY keda-operator${BIN_SUFFIX} /keda

USER 65532:65532

ENTRYPOINT ["/keda", "--zap-log-level=info", "--zap-encoder=console"]
