name: 'Release Kedify KEDA'

on:
  push:
    tags:
    - 'v*.*.*-*'

jobs:
  build-and-publish-images:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    name: build-images
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: "1.20"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release with goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_TAG: ${{ github.ref_name }}
