name: 'Release Kedify KEDA'

on:
  push:
    tags:
    - 'v*.*.*-*'

jobs:
  build-and-publish-images:
    timeout-minutes: 90
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    name: build-images
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU # required for multi-arch builds by GoReleaser
        uses: docker/setup-qemu-action@v3

      - name: Install arm C compiler toolchain # for boring crypto
        run: sudo apt-get update && sudo apt-get install -y gccgo-aarch64-linux-gnu

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Release with goreleaser
        timeout-minutes: 90
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --timeout 90m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_TAG: ${{ github.ref_name }}
